name: Add New Task

on:
  issues:
    types: [opened, reopened, edited]

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'data request')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x


  issue-jobs:
    if: contains(github.event.issue.labels.*.name, 'data request')
    runs-on: ubuntu-latest
    outputs:
      issue_number: ${{ steps.issue_parser.outputs.issue_number }}
      task_name: ${{ steps.issue_parser.outputs.task_name }}
      file_content: ${{ steps.issue_parser.outputs.file_content }}
      file_name: ${{ steps.issue_parser.outputs.file_name }}
    needs: build  

    steps:
    - name: Parse Task Issue
      id: issue_parser
      uses: brown-ccv/gh-actions/parse-task-issue@parse-task-issue
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Issue Commenter on failure
      if: ${{ failure() }}
      uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "This issue has failed. The YML file contents have not been filled properly (either the default text for the fields 
        is present or the required fields are missing)."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  pr-creation:
    if: contains(github.event.issue.labels.*.name, 'data request')
    runs-on: ubuntu-latest
    env:
      ISSUE_NUMBER: ${{needs.issue-jobs.outputs.issue_number}}
      TASK_NAME: ${{needs.issue-jobs.outputs.task_name}}
      FILE_NAME: ${{needs.issue-jobs.outputs.file_name}}
      FILE_DATA: ${{needs.issue-jobs.outputs.file_content}}
    needs: issue-jobs

    steps:
    - uses: actions/checkout@v2
      
    - name: Create file 
      working-directory: ./data
      run: echo "${{env.FILE_DATA}}" > '${{env.FILE_NAME}}.yml'

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: add ${{env.FILE_NAME}}
        title: 'Register ${{env.TASK_NAME}}'
        body: |
            Closes #${{env.ISSUE_NUMBER}}
        branch: create-pull-request/${{env.FILE_NAME}}
        labels: register task, automated pr
        assignees: fernandogelin, mcmcgrath13

    - name: Issue Commenter on success
      if: ${{ success() }}
      uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "We have created a PR for this issue - #${{ steps.cpr.outputs.pull-request-number }}. The YML file for the task data will be 
        entered into the data folder when the pull request is merged."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Issue Commenter on failure
      if: ${{ failure() }}
      uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "PR creation failed"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
